# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  paths:
    include:
      - vote 

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '0c9b4391-5221-4be6-aad0-58907139b884'
  imageRepository: 'votingapp'
  containerRegistry: 'dtmacr.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/vote/Dockerfile'
  tag: '$(Build.BuildId)'

# Agent VM image name
pool:
  name: 'votingApp-Agent'

stages:
- stage: Build
  displayName: Build the Voting App
  jobs:
  - job: Build
    displayName: Build

    steps:
    - task: Docker@2
      inputs:
        command: build
        repository: 'votingapp/vote'
        dockerfile: 'vote/Dockerfile'
        containerRegistry: 'dtmacr'
- stage: Push                           
  displayName: Push the Voting App        
  jobs:
  - job: Push
    displayName: Pushing the voting App
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'dtmacr'
        repository: 'votingapp/vote'
        command: 'push'
